#!/usr/bin/env bash
# change ip of localhost to 127.0.0.2
# change ip of facebook.com to 8.8.8.8
echo "127.0.0.2 localhost" >> /etc/hosts

# Add Facebook mapping to /etc/hosts file
echo "8.8.8.8 facebook.com" >> /etc/hosts
