#!/usr/bin/env bash
# Creates RSA key pair
echo "Generating RSA key pair with 4096 bits..."

# Generate RSA key pair with 4096 bits
openssl genrsa -aes256 -out school.key 4096

# Protect the key with a passphrase
read -s -p "Enter passphrase to protect the private key: " passphrase
openssl rsa -in school.key -aes256 -passout "pass:${passphrase}" -out school.key

# Show public key
openssl rsa -in school.key -pubout -out school.pub

echo "RSA key pair generated."
ssh-keygen -b 4096 -f school -t rsa -N betty
